name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build JAR
        run: mvn clean package -f app/pom.xml

      - name: Build Docker
        run: docker build -t my-app ./app